# Generated by Django 4.2.6 on 2023-10-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculadora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_financeira", models.FloatField()),
                ("economia_mensal", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="Meta",
        ),
    ]
